version: "3"
services:
    listing-service:
        build: './listing-service'
        depends_on:
            - listing-service-db
        volumes:
            - ./listing-service:/app
        ports:
            - 0.0.0.0:8080:8000
    
    listing-service-db:
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
        image: mysql:5.7.20
        ports:
            - 0.0.0.0:7200:3306

    user-service:
        build: './user-service'
        depends_on:
            - user-service-db
        volumes:
            - ./user-service:/app
        ports:
            - 0.0.0.0:8081:8000

    user-service-db:
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
        image: mysql:5.7.20
        ports:
            - 0.0.0.0:7201:3306