version: "3.1"
services:
    listing-service:
        build: './listing-service'
        depends_on:
            - mongo
        volumes:
            - ./listing-service:/app
        ports:
            - 0.0.0.0:8080:8000
        environment: 
            - MONGO_USERNAME=end
            - MONGO_PASSWORD=game
            - MONGO_HOSTNAME=mongo
            - MONGO_PORT=27017
            - MONGO_DB=test
        links:
            - mongo

    # mongo-express:
    mongo-express:
        image: mongo-express
        restart: always
        ports: 
            - 8081:8081
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=end
            - ME_CONFIG_MONGODB_ADMINPASSWORD=game


    #mongo storage
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        ports:
            - 0.0.0.0:27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=end
            - MONGO_INITDB_ROOT_PASSWORD=game
            